default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DB_NAME"] %>

test:
  <<: *default
  database: earthquakes_api_test

production:
  <<: *default
  database: <%= ENV["DB_NAME_PROD"]%>
  username: <%= ENV["DB_USERNAME_PROD"]%>
  password: <%= ENV["DB_PASSWORD_PROD"] %>
  url: <%= ENV['DB_URL_PROD'] %>
