default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

development:
  <<: *default
  database: earthquakes_api_development

test:
  <<: *default
  database: earthquakes_api_test

production:
  <<: *default
  database: <%= ENV['DBNAME']%>
  username: <%= ENV['DBUSERNAME']%>
  password: <%= ENV['DBPASSWORD'] %>
  url: <%= ENV['DBURL'] %>
